### ISSUE TITLE
Descoberta das habilidades

### ISSUE THREAD

**Issue by vitor-abel** [DarksunTeam/Monstreador#1]
**Descreva aqui a sua sugestão**
Realizar um levantamento das habilidades que serão incluídas no pré-cadastramento inicial da ferramenta.

**Story Points**
5 pontos

**Em que parte do sistema esta funcionalidade entraria**
No cadastro de monstros.

**Como você gostaria**
Gostaria que fosse feito um levantamento com base nos materiais do livro que foi escolhido como base para a ferramenta.

**Utilidade**
Informar as habilidades que serão utilizadas no sistema.

**Comment by Flaigor** [comment]
Arquivo docx com a lista de habilidade levantadas do livro do Tormenta20

[Habilidades de Criaturas.docx](https://github.com/DarksunTeam/Monstreador/files/8767136/Habilidades.de.Criaturas.docx)
