### ISSUE TITLE
Criação de um Wireframe

### ISSUE THREAD

**Issue by coppolaop** [DarksunTeam/Monstreador#20]
Descreva aqui a sua sugestão
Gostaria que fossem criados alguns wireframes para representar as telas da aplicação na primeira versão e dar base para o desenvolvimento até o fim desta primeira entrega.

Story Points
8

Em que parte do sistema esta funcionalidade entraria
Em toda a parte visual da ferramenta.

Como você gostaria
Ideia inicial de cada tela para guiar o time de desenvolvimento.

Utilidade
Dar direção ao time.

**Comment by PhillipeRamos** [comment]
![Image](https://user-images.githubusercontent.com/50685920/185268994-3bd5d891-356d-400d-9a29-cc919484f833.jpg)


![Image](https://user-images.githubusercontent.com/50685920/185269042-07f23280-bd64-4c86-9648-9687f6592527.jpg)



![Image](https://user-images.githubusercontent.com/50685920/185269058-a14e22e9-ef00-45b0-a5d8-aeb3a44993be.jpg)



![Image](https://user-images.githubusercontent.com/50685920/185269082-c83b5a78-9557-45fb-a89a-d590dd08b18c.jpg)

**Comment by PhillipeRamos** [comment]
Entendemos que a tarefa foi finalizada pois o wireframe foi devidamente entregue.
